module dls2_interfaces {
  	module msg {
		struct ArmBlindState
		{
			// Header
			string frame_id;
			unsigned long sequence_id;
			double timestamp;

			string robot_name;


			double arm_joints_position[6];
			double arm_joints_velocity[6];
			double arm_joints_effort[6];

			double arm_gripper_position;
			double arm_gripper_velocity;
			double arm_gripper_effort;
		};
	};
};
