#include "DlsAnnotation.idl"
#include "Pose.idl"
#include "Screw.idl"

module dls2_interfaces {
  	module msg {
				@Robot
				struct BaseState
				{
				// Header
					string frame_id;
					unsigned long sequence_id;
					double timestamp;

					string robot_name;

					// Base Pose
					dls2_interfaces::msg::Pose pose;

					// Base velocity
					dls2_interfaces::msg::Screw velocity;

					// Base acceleration
					dls2_interfaces::msg::Screw acceleration;

					// Stance status
					@LimbDataMap sequence<boolean> stance_status;
				};
	};
};
