#include "DlsAnnotation.idl"

module dls2_interfaces {
  	module msg {
				@Robot @Eigen
				struct BlindState
				{
					// Header
					string frame_id;
					unsigned long sequence_id;
					double timestamp;
					string robot_name;
					@JointDataMap sequence<string> joints_name;
					@JointState sequence<double> joints_position;
					@JointState sequence<double> joints_velocity;
					@JointState sequence<double> joints_acceleration;
					@JointState sequence<double> joints_effort;
					@JointState sequence<double> joints_temperature;
					@LimbDataMap sequence<boolean> feet_contact;
					@LimbDataMap_EigenVector3 sequence<double> current_feet_positions;
				};
  	};
};