@annotation Robot{};
@annotation Eigen{};
@annotation JointState{};
@annotation JointDataMap{};
@annotation LimbDataMap{};
// LimbDataMap where each lib data is of type Eigen::Vector3d
@annotation LimbDataMap_EigenVector3{};
@annotation EigenMatrix{
    uint32 n_rows;
    uint32 n_cols;
};