FROM nvidia/cuda:12.8.0-devel-ubuntu22.04


# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    CONDA_DIR=/opt/conda \
    PATH=/opt/conda/bin:$PATH

    
# Install tkinter, pip, and gedit
RUN apt-get update && apt-get install -y python3-tk
RUN apt-get update && apt-get install -y python3-pip
RUN apt-get update && apt-get install -y gedit


# Install git
RUN apt-get update && apt-get install -y git


# Install Miniforge
RUN apt-get update && \
    apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git && \
    wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O /tmp/miniforge.sh && \
    bash /tmp/miniforge.sh -b -p $CONDA_DIR && \
    rm /tmp/miniforge.sh && \
    conda init bash && \
    conda clean -afy

# Create and activate the conda environment
# Copy the environment file
COPY mamba_environment_ros2.yaml /tmp/mamba_environment_ros2.yaml
RUN conda env create -f /tmp/mamba_environment_ros2.yaml

#SHELL COLOR
SHELL ["/bin/bash", "-c"]
RUN echo 'export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;37m\]\u\[\033[00m\]@\[\033[01;32m\]\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] "'  >> /root/.bashrc

# Set the shell to use the conda environment
SHELL ["conda", "run", "-n", "trash_collection_isaaclab_ros2_env", "/bin/bash", "-c"]


# Set the shell to bash and configure the shell prompt and aliases
RUN echo 'conda activate trash_collection_isaaclab_ros2_env' >> /root/.bashrc

# Set the working directory and source the bashrc file
WORKDIR /home
RUN source /root/.bashrc